// Generated by Tiger,2016/04/26
'use strict';

module.exports = function (grunt) {

  // 任务运行时间
  require('time-grunt')(grunt);

  // 自动加载任务(任务管理器)
  require('jit-grunt')(grunt, {
    useminPrepare: 'grunt-usemin'
  });

  grunt.loadNpmTasks('grunt-css-sprite');
  // 配置程序路径
  var appConfig = {
    app: 'app',
    dist: 'dist'
  };
  // 如果 Gruntfile.js 编码为 gbk，打开此注释
  // grunt.file.defaultEncoding = 'gbk';
  var Gpkg = grunt.file.readJSON('abc.json');
  var imgBase = Gpkg.imgBase;
  var VERSION = Gpkg.version;
  //任务配置
  grunt.initConfig({

    // 从 abc.json 中读取配置项
    abcpkg: grunt.file.readJSON('abc.json'),
    // 项目设置
    yeoman: appConfig,
    sprite: {
      options: {
        // sprite背景图源文件夹，只有匹配此路径才会处理，默认 images/slice/
        imagepath: 'app/act/dreamteam/img/gj/',
        // 映射CSS中背景路径，支持函数和数组，默认为 null
        imagepath_map: null,
        // 雪碧图输出目录，注意，会覆盖之前文件！默认 images/
        spritedest: 'app/act/dreamteam/images/',
        // 替换后的背景路径，默认 ../images/
        spritepath: 'app/act/dreamteam/images/',
        // 各图片间间距，如果设置为奇数，会强制+1以保证生成的2x图片为偶数宽高，默认 0
        padding: 0,
        // 是否使用 image-set 作为2x图片实现，默认不使用
        useimageset: false,
        // 是否以时间戳为文件名生成新的雪碧图文件，如果启用请注意清理之前生成的文件，默认不生成新文件
        newsprite: false,
        // 给雪碧图追加时间戳，默认不追加
        spritestamp: true,
        // 在CSS文件末尾追加时间戳，默认不追加
        cssstamp: true,
        // 默认使用二叉树最优排列算法
        algorithm: 'binary-tree',
        // 默认使用`pixelsmith`图像处理引擎
        engine: 'pixelsmith'
      },
      autoSprite: {
        files: [{
          // 启用动态扩展
          expand: true,
          // css文件源的文件夹
          cwd: 'app/act/dreamteam/css/',
          // 匹配规则
          src: '*.css',
          // 导出css和sprite的路径地址
          dest: 'app/act/dreamteam/css/',
          // 导出的css名
          ext: '.sprite.css'
        }]
      }
    },
    //替换文件中的一些全局变量
    replace: {
      desktop: {
        options: {
          variables: {
            'IMGURL':imgBase["desktop"],
            'TIMESTAMP':VERSION+'_'+Date.now(),
            'VERSION':VERSION,
            "MINEXT":'',
            '1PXIMG':'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAAAXRSTlMAQObYZgAAAApJREFUCNdjYAAAAAIAAeIhvDMAAAAASUVORK5CYII='
          },
          prefix: '@@'
        },
        files: [
          {
            expand: true,
            cwd: '<%= yeoman.dist %>',
            dest: '<%= yeoman.dist %>',
            src: ['{,**/}*.{html,js,css}']
          }
        ]
      },
      production: {
        options: {
          variables: {
            'IMGURL':imgBase["production"],
            'TIMESTAMP':VERSION+'_'+Date.now(),
            'VERSION':VERSION,
            "MINEXT":'.min',
            '1PXIMG':'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAAAXRSTlMAQObYZgAAAApJREFUCNdjYAAAAAIAAeIhvDMAAAAASUVORK5CYII='
          },
          prefix: '@@'
        },
        files: [
          {
            expand: true,
            cwd: '<%= yeoman.dist %>',
            dest: '<%= yeoman.dist %>',
            src: ['{,**/}*.{html,js,css}']
          }
        ]
      }
    },
    // 监听文件
    watch: {
      'all': {
        options: {
          livereload: '<%=connect.options.livereload%>'  //监听前面声明的端口  35729
          // livereload: true
        },
        files: ['<%= yeoman.app %>/{,*/,*/*/}*.js','<%= yeoman.app %>/{,*/,*/*/}*.html','<%= yeoman.app %>/{,*/,*/*/}*.css','<%= yeoman.app %>/{,*/,*/*/}*.less'],
        tasks: [ 'demobuild' ]
      }
    },

    // grunt服务器设置
    connect: {
      options: {
        port: 80,
        //默认就是这个值，可配置为本机某个 IP，localhost 或域名
        hostname: '*',
        livereload: 35729
      },
      livereload: {
        options: {
          open: false,//是否打开浏览器
          middleware: function (connect) {
            return [
              connect.static('.tmp'),
              connect.static(appConfig.dist)
            ];
          }
        }
      },
      dist: {
        options: {
          open: false,  
          base: '<%= yeoman.dist %>'
        }
      }
    },

    // 文件清理
    clean: {
      dist: {
        files: [{
          dot: true,
          src: [
            '.tmp',
            '<%= yeoman.dist %>/{,*/}*',
            '!<%= yeoman.dist %>/.git{,*/}*'
          ]
        }]
      },
      server: '.tmp'
    },

    // 给css、min.css加前缀
    postcss: {
      options: {
        processors: [
          require('autoprefixer-core')({browsers: ['last 2 version','ie 8','ie 9']})
        ]
      },
      server: {
        options: {
          map: true
        },
        files: [{
          expand: true,
          cwd: '.tmp/styles/',
          src: '{,*/}*.css',
          dest: '.tmp/styles/'
        }]
      },
      dist: {
        files: [{
          expand: true,
          cwd: '.tmp/styles/',
          src: '{,*/}*.css',
          dest: '.tmp/styles/'
        }]
      }
    },

    // 重命名文件,避免缓存
    filerev: {
      dist: {
        src: [
          '<%= yeoman.dist %>/scripts/{,*/,*/*/}*.js',
          '<%= yeoman.dist %>/styles/{,*/}*.css',
          '<%= yeoman.dist %>/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}',
          '<%= yeoman.dist %>/styles/fonts/*'
        ]
      }
    },

    // 读取HTML usemin,使智能自动的构建
    // concat, minify and revision files.在内存中创建配置
    // 可操作的其他任务
    useminPrepare: {
      html: '<%= yeoman.app %>/index.html',
      options: {
        dest: '<%= yeoman.dist %>',
        flow: {
          html: {
            steps: {
              js: ['concat', 'uglifyjs'],
              css: ['cssmin']
            },
            post: {}
          }
        }
      }
    },

    // 基于 filerev 和 useminPrepare 配置执行重写
    usemin: {
      html: ['<%= yeoman.dist %>/{,*/,*/*/}*.html'],
      css: ['<%= yeoman.dist %>/styles/{,*/}*.css'],
      js: ['<%= yeoman.dist %>/scripts/{,*/,*/*/}*.js'],
      options: {
        assetsDirs: [
          '<%= yeoman.dist %>',
          '<%= yeoman.dist %>/images',
          '<%= yeoman.dist %>/styles'
        ],
        patterns: {
          js: [[/(images\/[^''""]*\.(png|jpg|jpeg|gif|webp|svg))/g, 'Replacing references to images']]
        }
      }
    },

    // 压缩CSS 
    cssmin: {
      main: {
        files: [
          {
            expand: true,
            cwd: '<%= yeoman.dist %>',
            src: ['**/*.css', '!**/*-min.css', '!**/*.less.css', '!**/*.scss.css'],
            dest: '<%= yeoman.dist %>',
            ext: '.min.css'
          }
        ]
      }
    },
    // 压缩JS
    uglify: {
      options: {
        banner: '/*! Generated by Tiger: <%= abcpkg.name %> */\n',
        // beautify:true,
        // preserveComments:false,
        // compress:true
          // mangle: false
      },
      main: {
        files: [
          {
            expand: true,
            cwd: '<%= yeoman.dist %>',
            src: ['**/*.js','**/*.*.js','!**/*.min.js'],
            dest: '<%= yeoman.dist %>',
            ext: '.min.js'
          }
        ]
      }
    },

    // svgmin: {
    //   dist: {
    //     files: [{
    //       expand: true,
    //       cwd: '<%= yeoman.app %>/images',
    //       src: '{,*/}*.svg',
    //       dest: '<%= yeoman.dist %>/images'
    //     }]
    //   }
    // },
    //压缩html文件
    htmlmin: {
      dist: {
        options: {
          collapseWhitespace: true,
          conservativeCollapse: true,
          collapseBooleanAttributes: true,
          removeCommentsFromCDATA: true
        },
        files: [{
          expand: true,
          cwd: '<%= yeoman.dist %>',
          src: ['{*,*/,*/*/}*.html'],
          dest: '<%= yeoman.dist %>'
        }]
      }
    },
    //less
   less: {
      main: {
        files: [{
          expand: true,
          cwd: '<%= yeoman.app %>',
          src: ['**/*.less'],
          dest: '<%= yeoman.dist %>',
          ext: '.css'
        }]
      }
    },
    //引入文件
    import:{
      main: {
        files: [{
          //启用动态扩展
          expand: true,
          // css文件源的文件夹
          cwd: '<%= yeoman.dist %>',
          // 匹配规则
          src: ['**/*.html'],
          //导出的网页存放目录
          dest: '<%= yeoman.dist %>',
          // 导出的网页扩展名
          ext: '.html'
        }]
      }
    },
    // 复制文件到dist
    copy: {
      dist: {
        files: [{
          expand: true,
          dot: true,
          cwd: '<%= yeoman.app %>',
          dest: '<%= yeoman.dist %>',
          src: [
            '*{,*/,*/*/}*.{ico,png,jpg,gif,txt,js,css,jpeg,html,htm,json,mp3,swf}',
            //'styles/fonts/{,*/}*.*'
          ]
        }, {
          expand: true,
          cwd: '.tmp/images',
          dest: '<%= yeoman.dist %>/images',
          src: ['generated/*']
        }]
      },
      //临时文件
      styles: {
        expand: true,
        cwd: '<%= yeoman.app %>/styles',
        dest: '.tmp/styles/',
        src: '{,*/}*.css'
      }
    },

    //并行运行其他任务，加快构建过程
    concurrent: {
      server: [
        'copy:styles'
      ]
    }
  });
  grunt.registerTask("cssSprite",['sprite']);
  // 启动serve调试时的本地服务
  grunt.registerTask('serve', 'Compile then start a connect web server', function (target) {
    //线上
    if (target === 'dist') {
      return grunt.task.run(['build', 'connect:dist:keepalive']);
    }
    //默认
    grunt.task.run(['demobuild','connect:livereload','watch']);
  });
  // demobuild本地调式任务
  grunt.registerTask('demobuild', [
      'clean:dist',
      'concurrent:server',
      'copy:dist',
      'less',
      'postcss:server',
      'replace:desktop',
      'import'
  ]);
  // 启动build打包线上代码
  grunt.registerTask('build', [
    'clean:dist',
    'useminPrepare',
    'concurrent:server',
    //'concat',
    'copy:dist',
    'less',
    'postcss',
    'replace:production',
    'cssmin',
    'uglify',
    //'filerev',
    'usemin',
    'import',
    'htmlmin'
  ]);
  //默认构建流程
  grunt.registerTask('default', [
    /*'newer:jshint',
    'newer:jscs',
    'test',*/
    'build'
  ]);
};
